sudo: false
dist: trusty
language: rust
cache: cargo
rust: nightly-2019-08-21 # minimum required version for async/await

before_script:
  - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
  - (test -x $HOME/.cargo/bin/mdbook || cargo install --vers "0.3.1" --debug --force mdbook)
  - (test -x $HOME/.cargo/bin/mdbook-linkcheck || cargo install --vers "0.3.1" --debug --force mdbook-linkcheck)
  - cargo install-update -a

script:
  - mdbook build
  - cargo test --all --manifest-path=./examples/Cargo.toml --target-dir ./target

env:
  RUSTINFRA_DEPLOY_DIR: book/html
import:
  - rust-lang/simpleinfra/travis-configs/static-websites.yml
